# TEST: Load data for the first time

## 1. Load GeoTIFF

In [1]:
# check current python version and environment
!python --version
!where python 

Python 3.13.0
c:\Users\simon\anaconda3\envs\test_environment\python.exe
C:\Users\simon\anaconda3\python.exe
C:\Users\simon\AppData\Local\Microsoft\WindowsApps\python.exe


In [2]:
# used python-interpreter
import sys
print(sys.executable)

c:\Users\simon\anaconda3\envs\test_environment\python.exe


In [3]:
# install and import required rasterio package
try:
    import rasterio
except:
    %pip install rasterio
    import rasterio

In [4]:
import rasterio.features
import rasterio.warp

In [5]:
# load file path of first GeoTIFF
file_path = r"D:\Drohne\1_OHB\1_OHB_Normalbetrieb\1_OHB_September_2021\Outputs\GeoTIFF\Abschnitt_01_tif.tif"

In [ ]:
try:
    with rasterio.open(file_path) as src: # src = stored datasetReader-object > is able to read raster and meta data 
        OHB1_Sept21_ABO1_data = src.read()  # reads raster data as NumPy-Array
        OHB1_Sept21_ABO1_profile = src.profile  # meta data like coordinate system, resolution, datatype
except FileNotFoundError:
    print(f"Error: File not found at '{file_path}'. Please check the path.")
except rasterio.errors.RasterioIOError as e:
    print(f"Error: Could not open the GeoTIFF file. {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

In [ ]:
print(OHB1_Sept21_ABO1_data)
# OHB1_Sept21_ABO1_data.view()

[[[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]]


In [ ]:
OHB1_Sept21_ABO1_data.shape, OHB1_Sept21_ABO1_data.dtype, type(OHB1_Sept21_ABO1_data)

((4, 35244, 17191), dtype('uint8'), numpy.ndarray)

In [35]:
print(dir(OHB1_Sept21_ABO1_data))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'

In [37]:
OHB1_Sept21_ABO1_data.mean()


np.float64(176.89205050216543)

In [ ]:
# coordninate system
crs_1 = src.crs
# geographical extent of the data (bounding box)
print(src.bounds)

# meta data
print(OHB1_Sept21_ABO1_profile)

BoundingBox(left=11.26459149229245, bottom=48.7455106686141, right=11.268291511222449, top=48.750527052866104)
{'driver': 'GTiff', 'dtype': 'uint8', 'nodata': None, 'width': 17191, 'height': 35244, 'count': 4, 'crs': CRS.from_wkt('GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]'), 'transform': Affine(2.1522999999995117e-07, 0.0, 11.26459149229245,
       0.0, -1.4233300000006033e-07, 48.750527052866104), 'blockxsize': 256, 'blockysize': 256, 'tiled': True, 'compress': 'lzw', 'interleave': 'pixel'}


In [41]:
try:
    import matplotlib as plt
except:
    %pip install matplotlib
    import matplotlib as plt

In [ ]:
# plot the GeoTiff 
plt.imshow(OHB1_Sept21_ABO1_data[0], cmap='gray')  # visalization with grey values
plt.colorbar(label='pixel values')
plt.title("First band")
plt.show()

AttributeError: module 'matplotlib' has no attribute 'imshow'

In [ ]:
if data.shape[0] >= 3:  # Überprüft, ob mindestens 3 Bänder vorhanden sind
    rgb_image = data[:3].transpose(1, 2, 0)  # Bänder transponieren
    plt.imshow(rgb_image)
    plt.title("RGB GeoTIFF als Bild")
    plt.axis('off')  # Achsen ausblenden
    plt.show()
else:
    print("Das GeoTIFF hat weniger als 3 Bänder, daher kein RGB-Bild.")

In [43]:
pip list | findstr matplotlib

matplotlib                  3.9.2Note: you may need to restart the kernel to use updated packages.

matplotlib-inline           0.1.7
